# Generated by Django 5.1.6 on 2025-03-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
