# Generated by Django 5.1.6 on 2025-03-11 12:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categorii'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default='00.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='[Categorie]', max_length=100),
        ),
        migrations.AlterField(
            model_name='furnizor',
            name='address',
            field=models.CharField(default='[Bd. Preciziei nr. 24, Bloc A1, Ap.709]', max_length=100),
        ),
        migrations.AlterField(
            model_name='furnizor',
            name='authentic_rating',
            field=models.CharField(default='[5]', max_length=100),
        ),
        migrations.AlterField(
            model_name='furnizor',
            name='chat_resp_time',
            field=models.CharField(default='[100]', max_length=100),
        ),
        migrations.AlterField(
            model_name='furnizor',
            name='contact',
            field=models.CharField(default='[+40 (787) 763 178]', max_length=100),
        ),
        migrations.AlterField(
            model_name='furnizor',
            name='days_return',
            field=models.CharField(default='[30]', max_length=100),
        ),
        migrations.AlterField(
            model_name='furnizor',
            name='description',
            field=models.TextField(blank=True, default='[Descriere furnizor]', null=True),
        ),
        migrations.AlterField(
            model_name='furnizor',
            name='shipping_on_time',
            field=models.CharField(default='[60]', max_length=100),
        ),
        migrations.AlterField(
            model_name='furnizor',
            name='title',
            field=models.CharField(default='[Furnizor]', max_length=100),
        ),
        migrations.AlterField(
            model_name='furnizor',
            name='warranty_period',
            field=models.CharField(default='[30]', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='[Descriere produs]', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='[Produs.jpg]', upload_to=core.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, default='[Alte specificatii]', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='[Produs]', max_length=100),
        ),
    ]
